language: java

jdk:
  - openjdk6
# oraclejdk6 isn't supported

env:
  matrix:
    - SOLR_VERSION=3.6.2
    - SOLR_VERSION=4.2.0
    - SOLR_VERSION=4.4.0

script: "mvn install -Dsolr.version=${SOLR_VERSION}"

notifications:
  email:
  - ksclarke@gmail.com
  irc:
  - irc.freenode.org#freelibrary
