language: java

jdk:
  - openjdk6

env:
  matrix:
    - SOLR_VERSION=3.6.1 SOLR_SCOPE=3.x DEBUG=true
    - SOLR_VERSION=3.6.2 SOLR_SCOPE=3.x DEBUG=true
    - SOLR_VERSION=4.0.0 SOLR_SCOPE=4.x-1 DEBUG=true
    - SOLR_VERSION=4.1.0 SOLR_SCOPE=4.x-1 DEBUG=true
    - SOLR_VERSION=4.2.0 SOLR_SCOPE=4.x-1 DEBUG=true
    - SOLR_VERSION=4.2.1 SOLR_SCOPE=4.x-1 DEBUG=true
    - SOLR_VERSION=4.3.0 SOLR_SCOPE=4.x-2 DEBUG=true
    - SOLR_VERSION=4.3.1 SOLR_SCOPE=4.x-2 DEBUG=true
    - SOLR_VERSION=4.4.0 SOLR_SCOPE=4.x-2 DEBUG=true
    - SOLR_VERSION=4.5.0 SOLR_SCOPE=4.x-2 DEBUG=true
    - SOLR_VERSION=4.5.1 SOLR_SCOPE=4.x-2 DEBUG=true
    - SOLR_VERSION=4.6.0 SOLR_SCOPE=4.x-2 DEBUG=true

install: "mvn -DskipTests=true -Dsolr.version=${SOLR_VERSION} install"

before_script: "curl https://raw.github.com/ksclarke/travis-solr/develop/travis-solr.sh | SOLR_VERSION=${SOLR_VERSION} SOLR_CONFS=src/test/resources/schemas/${SOLR_SCOPE}/schema.xml SOLR_LIBS=`find . -name solr-iso639-filter-*.jar` bash"

script: "mvn -Ptravis -Dsolr.version=${SOLR_VERSION} install"

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
