language: java

jdk:
  - openjdk6
# oraclejdk6 isn't supported

env:
  matrix:
    - SOLR_VERSION=3.6.1 SOLR_SCOPE=3.x DEBUG=true ISO639_JAR=solr-iso639-filter-3.6.2.1-SNAPSHOT.jar
    - SOLR_VERSION=3.6.2 SOLR_SCOPE=3.x ISO639_JAR=solr-iso639-filter-3.6.2.1-SNAPSHOT.jar
    - SOLR_VERSION=4.2.0 SOLR_SCOPE=4.2 ISO639_JAR=solr-iso639-filter-4.2.0.1-SNAPSHOT.jar
    - SOLR_VERSION=4.2.1 SOLR_SCOPE=4.2 DEBUG=true ISO639_JAR=solr-iso639-filter-4.2.0.1-SNAPSHOT.jar
    - SOLR_VERSION=4.3.0 SOLR_SCOPE=4.x DEBUG=true ISO639_JAR=solr-iso639-filter-4.4.0.1-SNAPSHOT.jar
    - SOLR_VERSION=4.3.1 SOLR_SCOPE=4.x DEBUG=true ISO639_JAR=solr-iso639-filter-4.4.0.1-SNAPSHOT.jar
    - SOLR_VERSION=4.4.0 SOLR_SCOPE=4.x ISO639_JAR=solr-iso639-filter-4.4.0.1-SNAPSHOT.jar

install: "mvn -DskipTests=true -Dsolr.version=${SOLR_VERSION} install"

before_script: "curl https://raw.github.com/ksclarke/travis-solr/develop/travis-solr.sh | SOLR_VERSION=${SOLR_VERSION} SOLR_CONFS=src/test/resources/schemas/${SOLR_SCOPE}/schema.xml SOLR_JARS=target/${ISO639_JAR} bash"

script: "mvn -Ptravis -Dsolr.version=${SOLR_VERSION} install"

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: never
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
